In [ ]:
import pandas as pd
import numpy as np 


In [ ]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

In [ ]:
uniform(10,50,(2,3))

array([[46.01756877, 48.01552831, 19.67030016],
       [28.04022778, 41.69919743, 37.91744541]])

Dataset

In [ ]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [ ]:
dataset=pd.DataFrame(data)

In [ ]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [ ]:
x=dataset.drop('Target',axis=1)
y=dataset['Target']

In [ ]:
x

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [ ]:
Normalizer().fit_transform(x)

array([[0.42426407, 0.56568542, 0.70710678],
       [0.59628479, 0.74535599, 0.2981424 ],
       [0.89442719, 0.35777088, 0.26832816],
       [0.30769231, 0.23076923, 0.92307692],
       [0.16058632, 0.64234527, 0.74940282],
       [0.57207755, 0.66742381, 0.47673129]])

In [ ]:
x_norm=Normalizer(norm='max').fit_transform(x)

In [ ]:
x_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [ ]:
y

0    20
1    15
2    60
3    70
4    50
5    40
Name: Target, dtype: int64

In [ ]:
array(y)

array([20, 15, 60, 70, 50, 40])

In [ ]:
array(y).shape

(6,)

In [ ]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [ ]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [ ]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN from Scratch

In [ ]:
#weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
#weight_2=array([[.5],[.1]])

In [ ]:
weight_1

In [ ]:
output1=x_norm[0]@weight_1

In [ ]:
output1

array([0.56, 0.24])

In [ ]:
act_output=sigmoid(output1).numpy()
act_output

array([0.63645254, 0.55971365])

In [ ]:
pred_output=act_output@weight_2
pred_output

array([0.37419764])

Mean Squared Error

In [ ]:
y_true=y_norm[0][0]
y_pred=pred_output

In [ ]:
y_pred

array([0.37419764])

In [ ]:
y_true

0.2857142857142857

In [ ]:
mse(y_true,y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=0.007829303112763407>

In [ ]:
mse(y_true,y_pred).numpy()

0.007829303112763407